version: "3.5"
services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=EventsDatabase
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
